apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: application

spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: LoadBalancer